name: Ant Design

pr:
  branches:
    exclude:
      - gh-pages

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: site
  jobs:
    - job: Build_Site
      steps:
        - checkout: self
          displayName: 'Checkout'
          clean: true
          fetchDepth: 1
        - task: NodeTool@0
          displayName: 'Install Node.js'
          inputs:
            versionSpec: '12.13.1'
        - script: npm install
          displayName: 'Install modules'
        - script: npm run site
          displayName: 'Build sites'
        - script: ls -al _site/
          displayName: 'List build'