name: Ant Design

trigger: none

pr:
  autoCancel: true
  branches:
    exclude:
      - gh-pages

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: site
  jobs:
    - job: Build_Site
      steps:
        - script: |
            curl -X POST -u $(ACCESS_TOKEN) -H "Accept: application/json" -H "Content-Type:application/json" https://api.github.com/repos/zombiej/ant-design/issues/$(SYSTEM_PULLREQUEST_PULLREQUESTNUMBER)/comments -d '{ "body": "good!" }'
          displayName: 'Test comment'
        - checkout: self
          displayName: 'Checkout'
          clean: true
          fetchDepth: 1
        - task: NodeTool@0
          displayName: 'Install Node.js'
          inputs:
            versionSpec: '12.13.1'
        - script: npm install
          displayName: 'Install modules'
        - script: npm run site
          displayName: 'Build sites'
        - script: ls -al _site/
          displayName: 'List build'
        - script: |
            export DEPLOY_DOMAIN=https://preview-${SYSTEM_PULLREQUEST_PULLREQUESTNUMBER}-ant-design.surge.sh
            echo "Deploy to $DEPLOY_DOMAIN"
            npx surge --project ./_site --domain $DEPLOY_DOMAIN
          displayName: Deploy
        - task: GitHubComment@0
          displayName: 'Gtihub Comment'
          inputs:
            id: $(SYSTEM_PULLREQUEST_PULLREQUESTNUMBER)
            repositoryName: 'zombiej/ant-design'
            gitHubConnection: $(ACCESS_TOKEN)
            comment: |
              Deploy preview is ready:
              https://preview-${SYSTEM_PULLREQUEST_PULLREQUESTNUMBER}-ant-design.surge.sh
