name: Ant Design

pr:
  branches:
    exclude:
      - gh-pages

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: env
  jobs:
    - job: Nodes
      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '12.13.1'
        displayName: 'Install Node.js'