name: Ant Design

trigger: none

pr:
  autoCancel: true
  branches:
    exclude:
      - gh-pages

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: site
  jobs:
    - job: Build_Site
      steps:
        - script: export DEPLOY_DOMAIN=https://preview-${SYSTEM_PULLREQUEST_PULLREQUESTNUMBER}-ant-design.surge.sh
        - script: echo "It is $DEPLOY_DOMAIN"
        - checkout: self
          displayName: 'Checkout'
          clean: true
          fetchDepth: 1
        - task: NodeTool@0
          displayName: 'Install Node.js'
          inputs:
            versionSpec: '12.13.1'
        - script: npm install
          displayName: 'Install modules'
        - script: npm run site
          displayName: 'Build sites'
        - script: ls -al _site/
          displayName: 'List build'
        - script: ls -al _site/
          displayName: 'List build'
        - script: export DEPLOY_DOMAIN=https://preview-${SYSTEM_PULLREQUEST_PULLREQUESTNUMBER}-ant-design.surge.sh